FreeWheeling.UI/Controllers/RideController.cs
using FreeWheeling.Domain.Abstract;
using FreeWheeling.Domain.Entities;
using FreeWheeling.UI.DataContexts;
using FreeWheeling.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using FreeWheeling.UI.Filters;
using FreeWheeling.UI.Infrastructure;
using System.Globalization;
using PusherServer;
using System.Threading.Tasks;
using Microsoft.WindowsAzure.Storage;
using System.Configuration;
using Microsoft.WindowsAzure.Storage.Queue;
using Microsoft.ServiceBus.Notifications;

namespace FreeWheeling.UI.Controllers
{
    [Authorize]
    public class RideController : Controller
    {
        private IdentityDb idb = new IdentityDb();
        private ICycleRepository repository;
        private NotificationHubClient hubClient;

        public RideController(ICycleRepository repoParam)
        {
            repository = repoParam;
            var cn = "Endpoint=sb://bunchy-ns.servicebus.windows.net/;SharedAccessKeyName=DefaultFullSharedAccessSignature;SharedAccessKey=l+yxYaa2g7FcqmNAUrwX0K1Rq/dfFh2GpaYXMuuAHig=";
            hubClient = NotificationHubClient
                .CreateClientFromConnectionString(cn, "bunchy");
        }

        [Compress]
        public ActionResult Index(int groupid = -1, int rideid = -1, int InviteId = -1, string fromhome = "false")
        {
            var currentUser = idb.Users.Find(User.Identity.GetUserId());
            if (InviteId != -1)
            {
                if (repository.PrivateBunchInviteUserEmailNotSet(InviteId))
                {
                    repository.UpdateInvitePrivateUser(currentUser.Id, currentUser.Email, InviteId);
                    repository.Save();
                }
            }

            RideModelIndex RideModel = new RideModelIndex();
            Group _Group = repository.GetGroupByID(groupid);

            //If group is null, see if we can get the group from the rideid and if so recall action with just the groupid set.
            if (_Group == null)
            {
                _Group = repository.GetGroupByRideID(rideid);
                if (_Group != null)
                {
                    rideid = -1;
                    groupid = _Group.id;
                    return RedirectToAction("Index", new { groupid = _Group.id });
                }               
            }

            if (_Group == null)
            {
                GroupModel GroupModel = new GroupModel();
                GroupModel._Groups = repository.GetGroups().ToList();
                GroupModel.CurrentGroupMembership = repository.CurrentGroupsForUser(currentUser.Id);
                return RedirectToAction("index", "group", GroupModel);
            }

            //Just in case location ID has not been set, set to same as ride.
            if (currentUser.LocationID == null)
            {
                currentUser.LocationID = _Group.Location.id;
                idb.SaveChanges();
            }

            RideModelHelper _RideHelper = new RideModelHelper(repository);
            var t = Request.QueryString["groupId"];
            if (groupid != -1 || rideid != -1)
            {
                RideModel = _RideHelper.PopulateRideModel(rideid, groupid, currentUser.Id, true);
            }
            else
            {
                GroupModel GroupModel = new GroupModel();
                GroupModel._Groups = repository.GetGroups().ToList();
                GroupModel.CurrentGroupMembership = repository.CurrentGroupsForUser(currentUser.Id);
                return RedirectToAction("index", "group", GroupModel);
            }

            if (RideModel.Ride != null)
            {
            }
            else
            {
                GroupModel GroupModel = new GroupModel();
                GroupModel._Groups = repository.GetGroups().ToList();
                GroupModel.CurrentGroupMembership = repository.CurrentGroupsForUser(currentUser.Id);
                return RedirectToAction("index", "group", GroupModel);
            }

            RideModel.FromHome = fromhome;
            RideModel.IsFavourite = repository.IsInFavouriteList(RideModel.Group.id, currentUser.Id);
            if (_Group.Lat != null)
            {
                RideModel.lat = _Group.Lat;
            }

            if (_Group.Lng != null)
            {
                RideModel.lng = _Group.Lng;
            }

            if (RideModel.Group.IsPrivate)
            {
                if (!repository.IsInvitedToPrivateBunch(RideModel.Group.id, currentUser.Id))
                {
                    GroupModel GroupModel = new GroupModel();
                    GroupModel._Groups = repository.GetGroups().ToList();
                    GroupModel.CurrentGroupMembership = repository.CurrentGroupsForUser(currentUser.Id);
                    return RedirectToAction("index", "group", GroupModel);
                }
            }

            RideModel.RouteCount = repository.RouteCountForGroup(RideModel.Group.id);

            return View(RideModel);
        }

        [HttpPost]
        public JsonResult RemoveFromFavouriteListJSON(int id)
        {
            var currentUser = idb.Users.Find(User.Identity.GetUserId());
            Member _Member = repository.GetMemberByUserID(currentUser.Id);
            Group group = repository.GetGroupByID(id);
            CultureHelper _CultureHelper = new CultureHelper(repository);
            TimeZoneInfo TZone = _CultureHelper.GetTimeZoneInfo(currentUser.LocationID);
            repository.RemoveMember(currentUser.Id, group);
            repository.Save();

            Task T = new Task(() =>
            {
                Ride _Ride = repository.GetHomePageRideByUserID(currentUser.Id);
                if (_Ride.Group.id == id)
                {
                    repository.DeleteHomePageRide(currentUser.Id);
                }
            });

            T.Start();

            Task E = new Task(() =>
            {
                CloudStorageAccount storageAccount = CloudStorageAccount.Parse(
                ConfigurationManager.ConnectionStrings["AzureJobsData"].ConnectionString);

                // Create the queue client.
                CloudQueueClient queueClient = storageAccount.CreateCloudQueueClient();

                // Retrieve a reference to a queue.
                CloudQueue queue = queueClient.GetQueueReference("updatehomepage");

                // Create the queue if it doesn't already exist.
                queue.CreateIfNotExists();

                // Create a message and add it to the queue.
                CloudQueueMessage message = new CloudQueueMessage("Hello, World");
                queue.AddMessage(message);

            });

            E.Start();

            return Json(new
            {
                success = true,
                message = "Emails Sent",
                GroupId = 2
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult JoinJSON(int id)
        {
            var currentUser = idb.Users.Find(User.Identity.GetUserId());
            Member _Member = repository.GetMemberByUserID(currentUser.Id);
            Group group = repository.GetGroupByID(id);
            repository.AddMember(currentUser.Id, group);
            repository.Save();

            Task T = new Task(() =>
            {
                CloudStorageAccount storageAccount = CloudStorageAccount.Parse(
                ConfigurationManager.ConnectionStrings["AzureJobsData"].ConnectionString);

                // Create the queue client.
                CloudQueueClient queueClient = storageAccount.CreateCloudQueueClient();

                // Retrieve a reference to a queue.
                CloudQueue queue = queueClient.GetQueueReference("updatehomepage");

                // Create the queue if it doesn't already exist.
                queue.CreateIfNotExists();

                // Create a message and add it to the queue.
                CloudQueueMessage message = new CloudQueueMessage("Joined");
                queue.AddMessage(message);

            });

            T.Start();
            //To Do: Need to confirm if this is used as looks incorrect.
            return Json(new
            {
                success = true,
                message = "Emails Sent",
                GroupId = 2
            }, JsonRequestBehavior.AllowGet);
        }

        [Compress]
        public ActionResult ViewSingleRide(int RideId, string fromhome = "false")
        {
            //This action is nolonger needed but is use by the facebook links (need to fix this), 
            //so will just redirect to index action passing the ride id
            return RedirectToAction("Index", new
            {
                rideid = RideId
            });
        }

        public ActionResult SeeAllComments(int RideId, int GroupId, int PreviousID = -1)
        {
            AllRideComments _AllRideComments = new AllRideComments();
            _AllRideComments.RideId = RideId;
            _AllRideComments.GroupId = GroupId;
            _AllRideComments.Comments = repository.GetAllCommentsForRide(RideId);
            _AllRideComments.PreviousID = PreviousID;
            return View(_AllRideComments);
        }

        public ActionResult InviteOthersToBunch(int RideId, int PreviousID = -1)
        {
            Ride _Ride = repository.GetRideByIDIncludeGroup(RideId);
            InviteOthersToBunchModel _InviteOthersToBunchModel = new InviteOthersToBunchModel
            {
                RideId = _Ride.id,
                Name = _Ride.Group.name,
                RideDate = _Ride.RideDate.ToString("dd/MM/yyyy"),
                PreviousID = PreviousID
            };
            return View(_InviteOthersToBunchModel);
        }

        [HttpPost]
        public JsonResult InviteOthersToBunch(InviteOthersToBunchModel _InviteOthersToBunchModel)
        {

FreeWheeling.UI/Views/Ride/AddHocList.cshtml
@model FreeWheeling.UI.Models.AdHocRidesModel
@using FreeWheeling.Domain.Entities

@{
    ViewBag.Title = "Add Hoc bunches";
}

@Html.ActionLink("Back <---", "Index", "Home", null, new { @class = "btn btn-info", onclick = "ShowProgress();" })


<h2>Add Hoc bunches</h2>

@if (@Model._Ad_HocRide.Count > 0 )
{              
    foreach (Ad_HocRide item in @Model._Ad_HocRide)
    {
        <h3> <span class="label label-info">@item.Name </span></h3>
        <p></p>
        @item.RideDate.ToLongDateString() @Html.Raw(", ") @item.RideDate.ToShortTimeString()
        <p></p>
        @Html.ActionLink(string.Concat("View bunch Details"), "ViewAdHocRide", "Ride", new { adhocrideid = item.id }, new { @class = "btn btn-success", onclick = "ShowProgress();" })
        <hr />   
    }
}
 else
    {
       @Html.ActionLink("No Ad Hoc bunches yet, please create some!", "CreateAdHoc", "Group", null, new { @class = "btn btn-default", onclick = "ShowProgress();" })                
    }

<div class="loading" align="center">
    Loading. Please wait.<br />
    <br />
    <img src="~/Content/Images/loader.gif" alt="" />
</div>
@section scripts{
    <script>
        jQuery(document).ready(function () {
            HideProgress();
        });
    </script>
}

FreeWheeling.UI/Views/Ride/InviteOthersToBunch.cshtml
@model FreeWheeling.UI.Models.InviteOthersToBunchModel
@{
    ViewBag.Title = "Invite Others to Bunch";
}
<div class="row">
    @* I have used PreviousID here from the _KeenActions.cshtml file should at some date update to read better *@
    @Html.ActionLink(" ", "Index", "Ride", new { groupid = @Model.PreviousID }, new { @class = "glyphicon glyphicon-chevron-left", @style = "background-color: #FFF; color: #333333;", onclick = "ShowProgress();" })
    <p></p>
    <div class="btn-group btn-block col-xs-12 col-md-3 col-sm-6" style="margin-bottom:5px;width:100%;">
        <span class="btn btn-default btn-block">
            Invite Others : @Model.Name :
            Date: @Model.RideDate
        </span>
    </div>
    <p></p>
    <p>Hit the <b>Select a person</b> button to invite your first person.</p><p><b>Note:</b> Hit the select a person button each time you wish to add another person to this bunch</p>
    <p>When done hit the Send Invites button.</p>
    <hr />
    <div id="templated">
        @Html.HiddenFor(model => model.RideId, new { @id = "RideIdHidden" })
        <table>
            <tbody data-bind="template: { name: 'userRowTemplate', foreach: usersLines }"></tbody>
        </table>
        <script type="text/html" id="userRowTemplate">
            <tr>
                <td>
                    Enter User name or a valid email address <p></p>
                    <input placeholder="Bunchy username or email" class="form-control" id="InviteUser" data-bind="value: UserName, valueUpdate:'blur'" />
                    <p></p>
                    Hit Select a person again to invite another person!
                    <p></p>
                </td>
            </tr>
        </script>
        <p></p>
        <span><button class="btn btn-default btn-sm" data-bind="click: addUser">Select a person</button></span>
        <span><input class="btn btn-default btn-sm" onclick="ShowProgress();" data-bind="click: save" id="btnSubmit" type="submit" value="Send Invites" /></span>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/knockout")
    @Scripts.Render("~/bundles/jqueryui")
    <script type="text/javascript">
    $('body').on('focus', "#InviteUser", function () {
        $(this).autocomplete({
            source: '@Url.Action("GetNames","Group")'
        });
    })
    function UserModel() {

        var self = this;
        self.UserName = ko.observable();
    }
    var RideModel = function () {
        var self = this;
        self.usersLines = ko.observableArray([]);

        self.addUser = function () {
            self.usersLines.push(new UserModel);
        };

        self.save = function () {
            RideData = {
                InviteUsers: self.usersLines(),
                RideId: $('#RideIdHidden').val()
            };

            $.ajax({
                type: "POST",
                url: '@Url.Action("InviteOthersToBunch", "Ride")',
                data: ko.toJSON(RideData), //Convert the Observable Data into JSON
                contentType: "application/json",
                success: function (data, textStatus, jqXHR) {
                    var err = eval("(" + jqXHR.responseText + ")");
                    if (data.success == false) {
                        alert(err.Message);
                        HideProgress();
                    }

                    if (data.success == true) {
                        // alert(ko.toJSON(self));
                        HideProgress();
                        displayMessageAjax(data.message, "success", "BottomCentre", "tempoarayMessage");
                        var RId = $('#RideIdHidden').val();
                        //window.location.href = '@Url.Action("Index", "Ride")';
                        //window.location.href = '/Ride?rideid=' + RId;
                        setTimeout(function () {
                            window.location.href = '/Ride?rideid=' + RId; //will redirect to your blog page (an ex: blog.html)
                        }, 1000); //will call the function after 2 secs.
                        }
                    },
                    error: function () {
                        displayMessageAjax("Error", "error", "BottomCentre", "tempoarayMessage");
                    }
                });
            };
        }
        $(document).ready(function () {
            $('#InviteUser').autocomplete({
                source: '@Url.Action("GetNames","Group")'
        });
        ko.applyBindings(RideModel);
    })
    </script>
    }

FreeWheeling.UI/Views/Ride/SeeAllComments.cshtml
@model FreeWheeling.UI.Models.AllRideComments
@using FreeWheeling.Domain.Entities

@{
    ViewBag.Title = "See All Comments";
}
<div class="row">
    @if (@Model.PreviousID != -1)
    {
        @Html.ActionLink(" ", "Index", "Ride", new { RideId = @Model.PreviousID, Groupid = @Model.GroupId }, new { @class = "glyphicon glyphicon-chevron-left", @style = "background-color: #FFF; color: #333333;", onclick = "ShowProgress();" })
    }
    else
    {
        @Html.ActionLink(" ", "Index", "Ride", new { RideId = @Model.RideId, Groupid = @Model.GroupId }, new { @class = "glyphicon glyphicon-chevron-left", @style = "background-color: #FFF; color: #333333;", onclick = "ShowProgress();" })
    }
    <p></p>
    <div class="panel-group">
        <div class="panel panel-default SecondaryHeading panel-heading">
            <b>All Comments</b>
        </div>
        <div class="panel panel-default" style="padding:10px;">
            @foreach (Comment item in @Model.Comments)
            {
                <span>@item.userName :</span>
                <span style="font-style:italic">@item.CommentText</span>
                @:<p></p>
            }
        </div>
    </div>
</div>
@section scripts{
<script>
    jQuery(document).ready(function () {
        HideProgress();
    });
</script>
}

FreeWheeling.UI/Views/Ride/_Comments.cshtml
@model FreeWheeling.UI.Models.RideModelIndex
@using FreeWheeling.Domain.Entities;
@{
    List<Comment> comments = new List<Comment>();    
    int position = Convert.ToInt32(ViewData["position"]);
    int rideid = Model.Ride.id;
    int commentcount = Model.CommentCount;
    string submitid = "submit_First";
    string commenttextid = "CommentStringFirst";
    int parentid = Model.Ride.id;
    comments = Model.Comments;
    
    if (position == 2)
    {
        comments = Model.NextComments;
        rideid = Model.NextRide.id;
        commentcount = Model.NextCommentCount;
        commenttextid = "CommentStringSecond";
        submitid = "submit_Second";
    }
}
<div id="@("collapseCommentPanel" + @rideid)" style="padding-left:20px">
    @foreach (Comment item in @comments)
    {
        <span>@item.userName :</span>
        <span style="font-style:italic">@item.CommentText</span>
        @:<p></p>
        }
</div>
<div>
    @using (Ajax.BeginForm("AddComment", "Ride", new
                {
                    groupid = @Model.Group.id,
                    rideid = @rideid,
                    ParentRideID = @parentid
                }, new AjaxOptions
        {
            HttpMethod = "Post",
            OnSuccess = "CommentComplete",
            OnBegin = "ShowProgress"
        }))
    {
    <div class="form-group">
        @Html.TextBox("CommentString", null, new { @class = "form-control", id = @commenttextid, placeholder = "Enter comment" })
        <p></p>
        <span class="input-group-addon-C">
            <button class="btn btn-default btn-sm" id="@submitid" type="submit">Add comment</button>
        </span>
        @Html.ActionLink(string.Concat("View all (", @commentcount, ")"), "SeeAllComments", "Ride", new { RideId = @rideid, Groupid = @Model.Group.id }, new { @class = "btn btn-default btn-sm", onclick = "ShowProgress();", id = string.Concat("CommentCountSpanSeeAll", @rideid.ToString()) })
        <span id="@("CommentCountSpan" + @rideid)"></span>
    </div>
    }
</div>

FreeWheeling.UI/Views/Ride/_CommentsRandomAndSingle.cshtml
@model FreeWheeling.UI.Models.SingleRideAndRandomRideViewModel
@using FreeWheeling.Domain.Entities;

@{
    string type = ViewData["type"].ToString();
    int rideid;
    int groupid;
    int commentcount = Model.CommentCount;
    string submitid = "submit_First";
    string commenttextid = "CommentStringFirst";
    int parentid;
    List<Comment> commentssingle = Model.Comments;
    List<AdHocComment> commentsrandom = Model.RandomComments;

    if (type == "random")
    {
        groupid = -1;
        rideid = Model.RandomRide.id;
        parentid = -1;
    }
    else
    {
        rideid = Model.Ride.id;
        groupid = Model.Ride.Group.id;
        parentid = Model.Ride.id;
    }

    <div id="@("collapseCommentPanel" + @rideid)" style="padding-left:20px">
        @if (type == "single")
        {
            foreach (Comment item in @commentssingle)
            {
                <span>@item.userName :</span>
                <span style="font-style:italic">@item.CommentText</span>
                @:<p></p>
        }
        }
        @if (type == "random")
        {
            foreach (AdHocComment item in @commentsrandom)
            {
                <span>@item.userName :</span>
                <span style="font-style:italic">@item.CommentText</span>
                @:<p></p>
      }
        }
    </div>
<div>

@if (type == "single"){
    using (Ajax.BeginForm("AddComment", "Ride", new
                {
                    groupid = @groupid,
                    rideid = @rideid,
                    ParentRideID = @parentid
                }, new AjaxOptions
                {
                    HttpMethod = "Post",
                    OnSuccess = "CommentComplete",
                    OnBegin = "ShowProgress"
                }))
                {
                    <div class="form-group">
                    @Html.TextBox("CommentString", null, new { @class = "form-control", id = @commenttextid, placeholder = "Enter comment" })
                    <p></p>
                    <span class="input-group-addon-C">
                    <button class="btn btn-default btn-sm" id="@submitid" type="submit">Add comment</button>
                    </span>
                    @Html.ActionLink(string.Concat("View all (", @commentcount, ")"), "SeeAllComments", "Ride", new { RideId = @rideid, Groupid = @groupid }, new { @class = "btn btn-default btn-sm", onclick = "ShowProgress();", id = string.Concat("CommentCountSpanSeeAll", @rideid.ToString()) })
                    <span id="@("CommentCountSpan" + @rideid)"></span>
                    </div>
                }
}

@if (type == "random")
{
    using (Ajax.BeginForm("AddAdHocComment", "Ride", new
                {
                    adhocrideid = @rideid,
                }, new AjaxOptions
                {
                    HttpMethod = "Post",
                    OnSuccess = "CommentComplete",
                    OnBegin = "ShowProgress"
                }))
                {
                    <div class="form-group">
                    @Html.TextBox("CommentString", null, new { @class = "form-control", id = @commenttextid, placeholder = "Enter comment" })
                    <p></p>
                    <span class="input-group-addon-C">
                    <button class="btn btn-default btn-sm" id="@submitid" type="submit">Add comment</button>
                    </span>
                    @Html.ActionLink(string.Concat("View all (", @commentcount, ")"), "SeeAllAdHocComments", "Ride", new { adhocrideid = @rideid }, new { @class = "btn btn-default btn-sm", onclick = "ShowProgress();", id = string.Concat("CommentCountSpanSeeAll", @rideid.ToString()) })
                    
                    </div>
                }
}    
</div>
}   

FreeWheeling.UI/Views/Ride/_JsonFavIcon.cshtml
@model FreeWheeling.UI.Models.RideModelIndex
@if (@Model.IsFavourite)
{
    @Ajax.ActionLink(" ", "RemoveFromFavouriteListJSON",
                     new { id = @Model.Group.id },
                 new AjaxOptions
                 {
                     HttpMethod = "POST",
                     OnSuccess = "onsuccessremovefav",
                     OnBegin = "ShowProgress"
                 },
                 new
                 {
                     @class = "pull-right glyphicon glyphicon-star",
                     style = "color:#333333;",
                     onclick = "ShowProgress();",
                     @id = "RemoveFav"
                 })

    @Ajax.ActionLink(" ", "JoinJSON",
                     new { id = @Model.Group.id },
                 new AjaxOptions
                 {
                     HttpMethod = "POST",
                     OnSuccess = "onsuccessjoinfav",
                     OnBegin = "ShowProgress"
                 },
                 new
                 {
                     @class = "pull-right glyphicon glyphicon-star-empty",
                     style = "color:#333333;display:none;",
                     onclick = "ShowProgress();",
                     @id = "JoinFav"
                 })
}
else
{
    @Ajax.ActionLink(" ", "JoinJSON",
                     new { id = @Model.Group.id },
                 new AjaxOptions
                 {
                     HttpMethod = "POST",
                     OnSuccess = "onsuccessjoinfav",
                     OnBegin = "ShowProgress"
                 },
                 new
                 {
                     @class = "pull-right glyphicon glyphicon-star-empty",
                     style = "color:#333333;",
                     onclick = "ShowProgress();",
                     @id = "JoinFav"
                 })

    @Ajax.ActionLink(" ", "RemoveFromFavouriteListJSON",
                     new { id = @Model.Group.id },
                 new AjaxOptions
                 {
                     HttpMethod = "POST",
                     OnSuccess = "onsuccessremovefav",
                     OnBegin = "ShowProgress"
                 },
                 new
                 {
                     @class = "pull-right glyphicon glyphicon-star",
                     style = "display:none;color:#333333;",
                     onclick = "ShowProgress();",
                     @id = "RemoveFav"
                 })
}

FreeWheeling.UI/Views/Ride/_KeenActions.cshtml
@model FreeWheeling.UI.Models.RideModelIndex
@{
    int position = Convert.ToInt32(ViewData["position"]);
    
    int rideid = Model.Ride.id;
    int parentid = Model.Ride.id;
    int groupid = Model.Group.id;
    string onsuccesskeen = "KeenCompleteFirst";


    string inid = "InFirst";
    string outid = "OutFirst";
    string onwayid = "OnWayFirst";
    
    if (position == 2)
    {
        rideid = Model.NextRide.id;
        onsuccesskeen = "KeenCompleteNext";
        
        inid = "InNext";
        outid = "OutNext";
        onwayid = "OnWayNext";
    }


}
@Ajax.ActionLink(" ", "Attend",
            new { RideId = @rideid, commitment = "In", Groupid = @Model.Group.id, ParentRideID = @parentid },
                 new AjaxOptions
                 {
                     HttpMethod = "POST",
                     OnSuccess = @onsuccesskeen,
                     OnBegin = "ShowProgress"
                 },
                 new
                 {
                     @class = "btn glyphicon glyphicon-thumbs-up btn-lg",
                     style = "color:#333333",
                     onclick = "ShowProgress();",
                     @id = @inid
                 })

@Ajax.ActionLink(" ", "Attend",
            new { RideId = @rideid, commitment = "Out", Groupid = @Model.Group.id, ParentRideID = @parentid },
                 new AjaxOptions
                 {
                     HttpMethod = "POST",
                     OnSuccess = onsuccesskeen,
                     OnBegin = "ShowProgress"
                 },
                      new
                      {
                          @class = "btn glyphicon glyphicon-thumbs-down btn-lg",
                          style = "color:#333333",
                          onclick = "ShowProgress();",
                          @id = @outid
                      })

@Ajax.ActionLink("on way", "Attend",
                 new { RideId = @rideid, commitment = "OnWay", Groupid = @Model.Group.id, ParentRideID = @parentid },
                 new AjaxOptions
                 {
                     HttpMethod = "POST",
                     OnSuccess = onsuccesskeen,
                     OnBegin = "ShowProgress"
                 },
                 new
                 {
                     @class = "btn btn-default btn-sm",
                     style = "",
                     onclick = "ShowProgress();",
                     @id = onwayid
                 })
    @Html.ActionLink("invite", "InviteOthersToBunch", "Ride",
        new
        {
            RideId = @rideid,
            PreviousID = @groupid
        },
                new { @class = "btn btn-default btn-sm", onclick = "ShowProgress();", id = "InviteFirst", style = "padding-right:10px" })

FreeWheeling.UI/Views/Ride/_Routes.cshtml
@model FreeWheeling.UI.Models.RideModelIndex
@using FreeWheeling.Domain.Entities;
@using FreeWheeling.UI.Models;
@{
    List<RouteWithVoteCount> routes = new List<RouteWithVoteCount>();
    int position = Convert.ToInt32(ViewData["position"]);
    int rideid = Model.Ride.id;
    int routecount = Model.RouteCount;
    string submitid = "submit_First";
    string commenttextid = "CommentStringFirst";
    int parentid = Model.Ride.id;
    routes = Model.Routes;

    if (position == 2)
    {
        routes = Model.NextRoutes;
        rideid = Model.NextRide.id;
        commenttextid = "CommentStringSecond";
        submitid = "submit_Second";
    }
}
<div id="@("collapseCommentPanel" + @rideid)" style="padding-left:20px">
    @foreach (RouteWithVoteCount item in @routes)
    {
        if (item.Desc != null)
        {
            <div>
                @using (Ajax.BeginForm("Vote", "Ride", new
                {
                    routeid = @item.RouteId,
                    rideid = @rideid,
                    ParentRideID = @parentid
                }, new AjaxOptions
        {
            HttpMethod = "Post",
            OnSuccess = "VoteComplete",
            OnBegin = "ShowProgress"
        }))
            {
                    <div class="form-group">
                        <span>@item.Desc (@item.VoteCount vote/s)</span>
                        
                        <span class="input-group-addon-C">
                            <button class="pull-right btn btn-default btn-sm" id="@submitid" type="submit">Vote</button>
                        </span>
                        <p></p>
                        <div><a class="btn btn-sm btn-success " target="_blank" href="@item.MapURL">View Route</a></div>
                        <p></p>
                        <hr />
                    </div>
            }
            </div>       
        }
    }
</div>